### PR TITLE
Fixed withdrawitems

### PR DESCRIPTION
**Pull request by Mistgun**
Finally..

### CODE REVIEW

**Comment by Mistgun** [comment]
I've changed the way in which this function worked to more appropriate. IMHO it should withdraw items up_to_count, not just the count since it has more sense and everyone does that.
(ps. noone else use this function just me)

**Comment by rmobis** [comment]
I agree the expected behavior would be that it acts as `moveitemsupto`, but I'm not too comfortable with breaking backwards compatibility.

On the other hand, documentation for this function was never written (as far as I can tell) and I doubt it has wide usage, so I don't believe doing so would cause so much pain.

Any input on this, @lucasterra @leonardofalk ?

**Comment by leonardofalk** [comment]
Yeah, the expected behaviour was to work as `moteitemsupto`, my input is, leave the function as it is cuz I'm pretty sure it's very deprecated by now.

**Comment by Mistgun** [comment]
I just think we're not breaking backward compatibility cuz:
1. None of other functions in global libs uses this function
2. I haven't seen anybody using this function, seriously

**Comment by rmobis** [comment]
We are definitely breaking backwards compatibility, the question is how much that affects people.

**Comment by Mistgun** [comment]
Also how can we break compatibility when this function wasn't working properly cuz of bad 'from' parameter?

**Comment by rmobis** [comment]
That's a good point.

**Comment by rmobis** [comment]
Seeing as the function never worked (and therefore cannot actually break backwards compatibility) and this PR actually improves its functionality I'm voting in favor of merging it. Is anyone explicitly against this?

**Comment by rmobis** [comment]
Well, since no one raised a good enough point against merging it, I'm pushing it through.

**Pull request merged**
